name: Publish carbon-web-components to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --offline
      - name: Build project
        run: yarn build
      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 1
          skip-version-file: 'true'
          skip-commit: 'true'
          output-file: "false"
      - name: Create Github Release
        if: steps.publish.outputs.version != steps.publish.outputs['old-version']
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag: v${{ steps.publish.outputs.version }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
