name: publish

on:
  push:
    branches:
      - master
      - fix/publish-changelog

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --offline
      - name: Build project
        run: yarn build
      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
      - name: Create changelog
        if: steps.publish.outputs.version != steps.publish.outputs['old-version']
        run: |
          rm -f ./.npmrc
          npm install -g conventional-changelog-cli
          CHANGELOG=$(conventional-changelog -r 1)
      - name: Create Github Release
        if: steps.publish.outputs.version != steps.publish.outputs['old-version']
        uses: ncipollo/release-action@v1
        with:
          body: ${{ env.CHANGELOG }}
          tag: v${{ steps.publish.outputs.version }}
          commit: fix/publish-changelog
          token: ${{ secrets.GITHUB_TOKEN }}
